src/Entity/Offers.php
<?php

namespace App\Entity;

use App\Repository\OffersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OffersRepository::class)
 */
class Offers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Creator;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $modifier;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modifier_date;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfDelivery::class, inversedBy="offers")
     */
    private $offers_delivery;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $delivery;

    /**
     * @ORM\ManyToOne(targetEntity=BenefitType::class, inversedBy="offers")
     */
    private $offer_benefit;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\GreaterThan("today")
     */
    private $limitDate;

    public function __construct()
    {
        $this->creation_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreator(): ?string
    {
        return $this->Creator;
    }

    public function setCreator(string $Creator): self
    {
        $this->Creator = $Creator;

        return $this;
    }

    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    public function setModifier(?string $modifier): self
    {
        $this->modifier = $modifier;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getModifierDate(): ?\DateTimeInterface
    {
        return $this->modifier_date;
    }

    public function setModifierDate(?\DateTimeInterface $modifier_date): self
    {
        $this->modifier_date = $modifier_date;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getOffersDelivery(): ?TypeOfDelivery
    {
        return $this->offers_delivery;
    }

    public function setOffersDelivery(?TypeOfDelivery $offers_delivery): self
    {
        $this->offers_delivery = $offers_delivery;

        return $this;
    }

    public function getDelivery(): ?float
    {
        return $this->delivery;
    }

    public function setDelivery(float $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getOfferBenefit(): ?BenefitType
    {
        return $this->offer_benefit;
    }

    public function setOfferBenefit(?BenefitType $offer_benefit): self
    {
        $this->offer_benefit = $offer_benefit;

        return $this;
    }

    public function getLimitDate(): ?\DateTimeInterface
    {
        return $this->limitDate;
    }

    public function setLimitDate(?\DateTimeInterface $limitDate): self
    {
        $this->limitDate = $limitDate;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Entity\Offers;
use App\Form\OfferType;
use App\Form\NewofferType;
use App\Repository\OffersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @var OffersRepository
     */
    private $repository;

    public function __construct(OffersRepository $repository, EntityManagerInterface $em){
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        $offers = $this->repository->findAll();
        return $this->render('home/index.html.twig', [
            'offers' => $offers,
        ]);
    }

    /**
     * @Route("/offres/{id}", name="offer.show")
     */
    public function show($id): Response
    {
        $offer = $this->repository->find($id);
        return $this->render('home/show.html.twig', [
            'offer' => $offer,
        ]);
    }
    /**
     * @Route("/créer", name="offer.create")
     */
    public function create(Request $request)
    {
        $offer = new Offers();

        $form = $this->createForm(NewofferType::class, $offer);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($offer);
            $this->em->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('home/create.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/éditer/{id}", name="offer.edit")
     */
    public function edit($id, Request $request)
    {
        $offer = $this->repository->find($id);

        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('home/edit.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/dupliquer/{id}", name="offer.duplicate")
     */
    public function duplicate($id)
    {
        $offer = $this->repository->find($id);
        $duplicate_offer = clone $offer;
        $this->em->persist($duplicate_offer);
            $this->em->flush();
            return $this->redirectToRoute('home');

    }

    /**
     * @Route("/supprimer/{id}", name="offer.delete")
     */
    public function delete(Offers $offer) {
        $this->em->remove($offer);
        $this->em->flush();
        return $this->redirectToRoute('home');
    }
}

templates/home/create.html.twig
{% extends 'base.html.twig' %}
{% block title %} Créer une offre {% endblock %}
{% block body %}
<div class="container mt-4">
    <h1>  Modifier l'offre de {{ offer.creator }} </h1>
    {{ form_start(form) }}
        {{ form_label(form.Creator, 'Votre Nom Prénom')}}
        {{ form_widget(form.Creator)}}
        {{ form_label(form.amount, 'Valeur de l\'offre')}}
        {{ form_widget(form.amount)}}
        {{ form_label(form.limitDate, 'Date butoire')}}
        {{ form_widget(form.limitDate)}}
        {{ form_label(form.offers_delivery, 'système de réduction')}}
        {{ form_widget(form.offers_delivery)}} <br>
        {{ form_label(form.delivery, 'valeur de la réduction')}}
        {{ form_widget(form.delivery)}}
        {{ form_label(form.offer_benefit, 'Technicité')}}
        {{ form_widget(form.offer_benefit,)}} <br>
        <button class="btn btn-primary">Créer</button>
    {{ form_end(form) }}
    </div>
{% endblock %}

templates/home/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} Modifier l'offre de {{ offer.creator }} {% endblock %}
{% block body %}
    <div class="container mt-4">
    <h1>  Modifier l'offre de {{ offer.creator }} </h1>
    {{ form_start(form) }}
        {{ form_label(form.Creator, 'Créateur de l\'offre')}}
        {{ form_widget(form.Creator)}}
        {{ form_label(form.modifier, 'Votre Nom Prénom ( personne modifiant)')}}
        {{ form_widget(form.modifier)}}
        {{ form_label(form.amount, 'Valeur de l\'offre')}}
        {{ form_widget(form.amount)}}
        {{ form_label(form.offers_delivery, 'système de réduction')}}
        {{ form_widget(form.offers_delivery)}} <br>
        {{ form_label(form.delivery, 'valeur de la réduction')}}
        {{ form_widget(form.delivery)}}
        {{ form_label(form.offer_benefit, 'Technicité')}}
        {{ form_widget(form.offer_benefit,)}} <br>
        <button class="btn btn-primary">Editer</button>
    {{ form_end(form) }}
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} Liste des offres {% endblock %}
{% block body %}
    <div class="container">
        <h1>Les offres en cours </h1>
        {{ dump(offers[0])}}
        <div class="container col-2"><a href="{{ path('offer.create')}}" class="btn btn-success">Créer une offre</a></div>
        {% for offer in offers %}
        <div class="card mt-4">
            <div class="card-header">
                Par {{ offer.creator}}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ offer.amount }} €</h5>
                <p class="card-text">type de prestation : {{offer.offerbenefit.name}} <br>créé le {{offer.creationdate|date('d-m-Y')}}</p>
                <a href="{{ path('offer.show', {id: offer.id})}}" class="btn btn-primary">Voir l'offre en détail</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{offer.creator}} {% endblock %}
{% block body %}
    {{ dump(offer)}}
    <div class="container mt-4"> 
    <div class="row">
        <div class="col-10">
            <h1>{{offer.creator}}</h1> 
        </div>
        <div class="col-2">
            <a href="{{ path('offer.delete', {id: offer.id})}}" class="btn btn-danger">Supprimer</a>
        </div>
    </div>
    <h2> Créé le {{ offer.creationdate|date('d-m-Y')}}</h2>

    {% if offer.modifier == false %}

    <p><strong> Aucune modification effectuée </strong><p>

    {% else %}

    <p> Modification effectuée par <strong>{{ offer.modifier}}<strong> le <strong>{{offer.modifierdate|date('d-m-Y')}} à {{offer.modifierdate|date('H')}} heure {{offer.modifierdate|date('i')}}.<strong> </p>

    {% endif %}
    <p> Type de prestation : {{offer.offerbenefit.name}} </p>
    <p> Date butoire : {{offer.limitDate|date('d-m-Y')}} </p>
    {% if offer.delivery == false %}
    <h3> Valeur (aucune remise effectuée) : {{offer.amount}} €.</h3>
    {% else %}
    <p> Valeur : <strong>{{offer.amount}} €.</strong></p>
    <br> 
        {% if offer.offersdelivery.name == '%' %}
        remise prévue : {{offer.delivery}}%.<br>
        <h3>Valeur après remise : {{ offer.amount - (offer.amount/100)*offer.delivery}} €.</h3>
        {% else %}
        remise prévue : {{offer.delivery}} €.<br>
        <h3>Valeur après remise : {{ offer.amount - offer.delivery }} €.</h3>
        {% endif %}
    
    {% endif %}
    <div class="row">
        <div class="col-4">
            <a href="{{ path('offer.edit', {id: offer.id})}}" class="btn btn-warning">modifier l'offre</a>
        </div>
        <div class="col-6">
        </div>
        <div class="col-2">
            <a href="{{ path('offer.duplicate', {id: offer.id})}}" class="btn btn-warning">dupliquer l'offre</a>
        </div>
    </div>
    <div class="container col-2"><a href="{{ path('home')}}" class="btn btn-success">retour</a></div>
    </div>
{% endblock %}